
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-6pm-2
owner: ucsb-cs156-f23
repo_name: team02-f23-6pm-2
pull_requests: [{"author":{"id":"U_kgDOBdHvcw","is_bot":false,"login":"vedantshah99","name":"Vedant Shah"},"headRefName":"Vedant-ArticleTable","number":49,"title":"Vedant article table","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-2/pull/49"},{"author":{"id":"MDQ6VXNlcjcyODM5MjIz","is_bot":false,"login":"whuang602","name":"Will H."},"headRefName":"William-RecRequestController-Delete","number":48,"title":"wh - implemented recrequest controller delete","url":"https://github.com/ucsb-cs156-f23/team02-f23-6pm-2/pull/48"}]
